# app.yaml
application: xando-1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: rocket_engine.wsgi

libraries:
- name: django
  version: 1.3

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'